export const TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function presaleEnabled() view returns (bool)",
  "function tradingEnabled() view returns (bool)",
  "function paused() view returns (bool)",
  "function maxTransferAmount() view returns (uint256)",
  "function maxWalletAmount() view returns (uint256)",
  "function presaleContract() view returns (address)",
  "function treasury() view returns (address)",
  "function stakingPlatform() view returns (address)",
  "function airdropContract() view returns (address)",
  "function isExcludedFromLimits(address) view returns (bool)",
  "function owner() view returns (address)",
  "function setPresale(address) external",
  "function setTreasury(address) external",
  "function setLiquidityManager(address) external",
  "function setPostPresaleDistributor(address) external",
  "function liquidityManager() view returns (address)",
  "function postPresaleDistributor() view returns (address)",
  "function LIQUIDITY_SHARE() view returns (uint256)",
  "function DISTRIBUTOR_SHARE() view returns (uint256)",
  "event PostPresaleDistributorUpdated(address indexed distributor)",
  "event LiquidityManagerUpdated(address indexed liquidityManager)",
  "event UnsoldTokensAutoTransferred(address indexed liquidityManager, uint256 amount)",
  "event UnsoldTokensDistributed(uint256 toLiquidity, uint256 toDistributor)",
  "function setStakingPlatform(address) external",
  "function setAirdropContract(address) external",
  "function setPresaleEnabled(bool) external",
  "function setTradingEnabled(bool) external",
  "function setTransferLimits(uint256, uint256) external",
  "function excludeFromLimits(address, bool) external",
  "function pause() external",
  "function unpause() external",
  "function getTokenInfo() view returns (string, string, uint256, uint256, uint256, bool, bool, bool)"
];

export const PRESALE_ABI = [
  "function buyTokens() external payable",
  "function startPresale() external",
  "function stopPresale() external",
  "function updatePrice(uint256) external",
  "function updateLimits(uint256, uint256) external",
  "function setTreasury(address) external",
  "function setLiquidityManager(address) external",
  "function setPostPresaleDistributor(address) external",
  "function liquidityManager() view returns (address)",
  "function postPresaleDistributor() view returns (address)",
  "function LIQUIDITY_SHARE() view returns (uint256)",
  "function DISTRIBUTOR_SHARE() view returns (uint256)",
  "event PostPresaleDistributorUpdated(address indexed distributor)",
  "event LiquidityManagerUpdated(address indexed liquidityManager)",
  "event UnsoldTokensAutoTransferred(address indexed liquidityManager, uint256 amount)",
  "event UnsoldTokensDistributed(uint256 toLiquidity, uint256 toDistributor)",
  "function setWhitelistEnabled(bool) external",
  "function addToWhitelist(address[]) external",
  "function removeFromWhitelist(address[]) external",
  "function withdrawUnsoldTokens(uint256) external",
  "function withdrawBNB() external",
  "function pause() external",
  "function unpause() external",
  "function tokenPriceInBNB() view returns (uint256)",
  "function minPurchase() view returns (uint256)",
  "function maxPurchase() view returns (uint256)",
  "function presaleActive() view returns (bool)",
  "function whitelistEnabled() view returns (bool)",
  "function totalBNBRaised() view returns (uint256)",
  "function totalTokensSold() view returns (uint256)",
  "function totalParticipants() view returns (uint256)",
  "function isWhitelisted(address) view returns (bool)",
  "function paused() view returns (bool)",
  "function owner() view returns (address)",
  "function getUserInfo(address) view returns (uint256, uint256, bool)",
  "function getPresaleInfo() view returns (uint256, uint256, uint256, uint256, uint256, uint256, uint256, bool)"
];

export const TREASURY_ABI = [
  "function recordSaleRevenue(uint256) external",
  "function calculateTotalYields() view returns (uint256)",
  "function updatePoolAPY(uint256, uint256) external",
  "function togglePool(uint256, bool) external",
  "function authorizeSeller(address, bool) external",
  "function setStakingContract(address) external",
  "function distributeYields(address, uint256) external",
  "function emergencyWithdraw() external",
  "function totalBNBReceived() view returns (uint256)",
  "function totalBNBInvested() view returns (uint256)",
  "function totalYieldsDistributed() view returns (uint256)",
  "function authorizedSellers(address) view returns (bool)",
  "function owner() view returns (address)",
  "function getTreasuryStats() view returns (uint256, uint256, uint256, uint256)",
  "function getPoolStats(uint256) view returns (string, uint256, uint256, uint256, uint256, bool)",
  "function getAllPoolsStats() view returns (uint256[], uint256[], uint256[], uint256[], uint256[])"
];

export const STAKING_ABI = [
  "function stake(uint256) external",
  "function unstake(uint256) external",
  "function claimRewards() external",
  "function setRewardRate(uint256) external",
  "function setMinStakeAmount(uint256) external",
  "function depositRewards(uint256) external",
  "function emergencyWithdrawAll() external",
  "function pause() external",
  "function unpause() external",
  "function totalStaked() view returns (uint256)",
  "function totalStakers() view returns (uint256)",
  "function rewardRate() view returns (uint256)",
  "function minStakeAmount() view returns (uint256)",
  "function earned(address) view returns (uint256)",
  "function paused() view returns (bool)",
  "function owner() view returns (address)",
  "function userStakes(address) view returns (uint256, uint256, uint256, uint256)",
  "function getUserStakeInfo(address) view returns (uint256, uint256, uint256)",
  "function getStakingInfo() view returns (uint256, uint256, uint256, uint256, uint256)"
];

export const AIRDROP_ABI = [
  "function executeAirdrop(string, address[], uint256[]) external",
  "function singleAirdrop(address, uint256) external",
  "function claimAirdrop() external",
  "function hasClaimedPublic(address) view returns (bool)",
  "function totalPublicClaims() view returns (uint256)",
  "function maxTotalClaims() view returns (uint256)",
  "function claimAmount() view returns (uint256)",
  "function getPublicClaimStats() view returns (uint256, uint256, uint256, uint256)",
  "function withdrawTokens(uint256) external",
  "function burnTokens(uint256) external",
  "function pause() external",
  "function unpause() external",
  "function totalAirdrops() view returns (uint256)",
  "function totalTokensDistributed() view returns (uint256)",
  "function totalRecipients() view returns (uint256)",
  "function paused() view returns (bool)",
  "function owner() view returns (address)",
  "function getAirdropStats() view returns (uint256, uint256, uint256, uint256)",
  "function getCampaignInfo(uint256) view returns (string, uint256, uint256, uint256, bool)",
  "function getUserAirdropInfo(address) view returns (uint256, bool)"
];

export const LIQUIDITY_ABI = [
  "function createPool(uint256 dexId, uint256 tokenAmount) external payable",
  "function addLiquidity(uint256 dexId, uint256 tokenAmount) external payable",
  "function removeLiquidity(uint256 dexId, uint256 lpAmount) external",
  "function toggleDEX(uint256 dexId, bool enabled) external",
  "function updateDEXRouter(uint256 dexId, address newRouter) external",
  "function depositTokens(uint256 amount) external",
  "function withdrawTokens(uint256 amount) external",
  "function withdrawETH() external",
  "function owner() view returns (address)",
  "function dexHasPool(uint256) view returns (bool)",
  "function activePools() view returns (uint256)",
  "function getPoolCount() view returns (uint256)",
  "function getDEXInfo(uint256) view returns (string, address, bool, bool, uint256)",
  "function getAllDEXs() view returns (string[4], address[4], bool[4], bool[4])",
  "function getPoolInfo(uint256) view returns (string, address, uint256, uint256, uint256, uint256, bool)",
  "function getStats() view returns (uint256, uint256, uint256, uint256, uint256)"
];

export const TREASURY_V4_ABI = [
  "function claimYields() external",
  "function pendingYields(address) view returns (uint256)",
  "function totalBNBReceived() view returns (uint256)",
  "function totalBNBInVenus() view returns (uint256)",
  "function totalYieldsClaimed() view returns (uint256)",
  "function depositsEnabled() view returns (bool)",
  "function owner() view returns (address)",
  "function getTreasuryStats() view returns (uint256, uint256, uint256, uint256)",
  "function getFullStats() view returns (uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256)",
  "function getUserYieldInfo(address) view returns (uint256, uint256, uint256, uint256)",
  "function getHoldersCount() view returns (uint256)",
  "function getAllPoolsStats() view returns (uint256[], uint256[], uint256[], uint256[], uint256[])"
];

// ====================================================================
// NUEVOS CONTRATOS — añadidos en deployment v2
// ====================================================================

export const POST_PRESALE_DISTRIBUTOR_ABI = [
  // Reads
  "function dwallToken() view returns (address)",
  "function liquidityManager() view returns (address)",
  "function presaleContract() view returns (address)",
  "function cexReserveTotal() view returns (uint256)",
  "function cexWithdrawn() view returns (uint256)",
  "function cexUnlockTime() view returns (uint256)",
  "function CEX_TIMELOCK() view returns (uint256)",
  "function dripTotal() view returns (uint256)",
  "function dripReleased() view returns (uint256)",
  "function dripStartTime() view returns (uint256)",
  "function lastDripTime() view returns (uint256)",
  "function DRIP_INTERVAL() view returns (uint256)",
  "function DRIP_INSTALLMENTS() view returns (uint256)",
  "function initialized() view returns (bool)",
  "function owner() view returns (address)",
  "function getCEXReserveStatus() view returns (uint256 total, uint256 withdrawn, uint256 available, uint256 unlockTime, bool isLocked)",
  "function getDripStatus() view returns (uint256 total, uint256 released, uint256 remaining, uint256 nextReleaseTime, uint256 installmentSize, uint256 installmentsRemaining)",
  // Writes
  "function initialize() external",
  "function withdrawForCEX(address cexWallet, uint256 amount) external",
  "function releaseMonthlyDrip() external",
  // Events
  "event Initialized(uint256 totalAmount, uint256 cexReserve, uint256 dripAmount)",
  "event CEXWithdrawn(address indexed cexWallet, uint256 amount, uint256 timestamp)",
  "event DripReleased(uint256 installment, uint256 amount, uint256 timestamp)"
];

export const MARKETING_TREASURY_ABI = [
  // Reads
  "function dwallToken() view returns (address)",
  "function owner() view returns (address)",
  "function totalSpent() view returns (uint256)",
  "function totalReceivedBy(address) view returns (uint256)",
  "function totalSpentByCategory(bytes32) view returns (uint256)",
  "function CAT_INFLUENCER() view returns (bytes32)",
  "function CAT_LISTING() view returns (bytes32)",
  "function CAT_AUDIT() view returns (bytes32)",
  "function CAT_BOUNTY() view returns (bytes32)",
  "function CAT_OPERATIONS() view returns (bytes32)",
  "function CAT_OTHER() view returns (bytes32)",
  "function getPaymentCount() view returns (uint256)",
  "function getPayment(uint256 paymentId) view returns (address recipient, uint256 amount, string memory reason, bytes32 category, uint256 timestamp)",
  "function getRecentPayments(uint256 limit) view returns (tuple(address recipient, uint256 amount, string reason, bytes32 category, uint256 timestamp)[])",
  "function getBalance() view returns (uint256)",
  "function getTreasuryStats() view returns (uint256 currentBalance, uint256 totalSpentSoFar, uint256 totalPaymentsCount)",
  // Writes
  "function makePayment(address recipient, uint256 amount, string calldata reason, bytes32 category) external",
  "function makeBatchPayments(address[] calldata recipients, uint256[] calldata amounts, string[] calldata reasons, bytes32 category) external",
  // Events
  "event PaymentExecuted(uint256 indexed paymentId, address indexed recipient, uint256 amount, bytes32 indexed category, string reason, uint256 timestamp)"
];
